# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/arios/Projects/okaertool/src/XEM7310-A200/CPNAS_OKAERTool_xem7310.xdc

# XDC: new/debug.xdc

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_0_1/design_1_clk_wiz_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_1 || ORIG_REF_NAME==design_1_clk_wiz_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_0_0/design_1_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlslice_0_0 || ORIG_REF_NAME==design_1_xlslice_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_xlslice_0_1/design_1_xlslice_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_xlslice_0_1 || ORIG_REF_NAME==design_1_xlslice_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_OpenNas_Cascade_STER_0_2/design_1_OpenNas_Cascade_STER_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_OpenNas_Cascade_STER_0_2 || ORIG_REF_NAME==design_1_OpenNas_Cascade_STER_0_2} -quiet] -quiet

# IP: bd/design_1/ip/design_1_OpenNas_Parallel_STE_0_0/design_1_OpenNas_Parallel_STE_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_OpenNas_Parallel_STE_0_0 || ORIG_REF_NAME==design_1_OpenNas_Parallel_STE_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_okt_sno_top_0_0/design_1_okt_sno_top_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_okt_sno_top_0_0 || ORIG_REF_NAME==design_1_okt_sno_top_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_okt_top_0_2/design_1_okt_top_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_okt_top_0_2 || ORIG_REF_NAME==design_1_okt_top_0_2} -quiet] -quiet

# XDC: /home/arios/Projects/OpenNAS/created_projects/project/NAS_and_OKAERTool/NAS_and_OKAERTool.gen/sources_1/bd/design_1/design_1_ooc.xdc
